config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "main#index"

  get "about" => "about#index", as: "about"

  get "sign-up" => "registration#create"
  post "sign-up" => "registration#signup"

  get "sign-in" => "sessions#new"
  post "sign-in" => "sessions#create"
  delete "logout" => "sessions#logout"

  get "edit-password" => "passwords#edit"
  patch "update-password" => "passwords#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# email: string
# password_digest: string
# password: string ( virtual )
# password_confirmation: string ( virtual )
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, error: "You must be logged in to do that " if Current.user.nil?
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def index
  end
end

app/controllers/passwords_controller.rb
# frozen_string_literal: true

class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(update_password_params)
      redirect_to root_path, notice: "Password successfully updated !"
    else
      render :edit
    end
  end

  private
  def update_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registration_controller.rb
# frozen_string_literal: true

class RegistrationController < ApplicationController
  def create
    @user = User.new
  end

  def signup
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account successfully created !"
    else
      render :create
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? & user.authenticate(params[:password])
      session[:user_id] = user.id

      redirect_to root_path, notice: "Successfully Logged In !"
    else
      flash[:error] = "Invalid username or password !"
      render :new
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to root_path, notice: "Logged Out !"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweetsRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>


    <div class="container">
      <%= render partial: "shared/flash" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex justify-content-center align-items-center">
  <h1>Nice to have you here !!! Oooh yeeea</h1>
</div>

app/views/shared/_flash.html.erb
<div class="mt-4 mb-4">
  <% if flash[:notice] %>
    <div class="alert alert-info" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:error] %>

    <div class="alert alert-warning" role="alert">
      <%= flash[:error] %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "STweets", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto  mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-link">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>

          <li class="nav-link">
            <%= button_to "Log Out", logout_path, method: :delete, class: "btn btn-sm btn-outline-secondary" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign In", sign_in_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>